# Generated by Django 5.1.2 on 2025-02-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualizacion',
            options={'ordering': ['fecha']},
        ),
    ]
