# Generated by Django 5.1.2 on 2025-02-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_actualizacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
            },
        ),
        migrations.CreateModel(
            name='ProyectoTemario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Temario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='proyectos.comision')),
                ('proyectos', models.ManyToManyField(through='proyectos.ProyectoTemario', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Temario',
                'verbose_name_plural': 'Temarios',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('numero', 'comision')},
            },
        ),
        migrations.AddField(
            model_name='proyectotemario',
            name='temario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.temario'),
        ),
        migrations.AlterUniqueTogether(
            name='proyectotemario',
            unique_together={('temario', 'orden')},
        ),
    ]
