# Generated by Django 5.1.2 on 2025-02-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_comision_proyectotemario_temario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temario',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='proyectos.categoria'),
        ),
        migrations.DeleteModel(
            name='Comision',
        ),
    ]
