# Generated by Django 5.1.2 on 2025-02-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_temario_comision_delete_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('categoria_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_categorias_anteriores', to='proyectos.categoria')),
                ('categoria_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_categorias_nuevas', to='proyectos.categoria')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='historial_categorias',
            field=models.ManyToManyField(related_name='historial_proyectos', through='proyectos.HistorialCategoria', to='proyectos.categoria'),
        ),
    ]
