# Generated by Django 5.1.2 on 2025-02-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_remove_proyecto_historial_categorias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.categoria'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temario',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.categoria'),
        ),
        migrations.AlterField(
            model_name='temario',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
