# Generated by Django 5.1.2 on 2025-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_temario_creado_por_alter_proyecto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='numero',
            field=models.CharField(default=0, help_text='Formato: XXXX/XX', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('ley', 'Proyecto de Ley'), ('resolucion', 'Proyecto de Resolución')], default='ley', max_length=20),
        ),
    ]
