# Generated by Django 5.1.2 on 2025-03-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_proyecto_numero_proyecto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('tratandose', 'En tratamiento'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], default='pendiente', max_length=20)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.categoria')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_comisiones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Ruta de Comisión',
                'verbose_name_plural': 'Rutas de Comisiones',
                'ordering': ['orden'],
                'unique_together': {('proyecto', 'comision')},
            },
        ),
    ]
