# Generated by Django 5.1.2 on 2025-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0009_rutacomision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="titulo",
            field=models.CharField(max_length=1000),
        ),
    ]
