# Generated by Django 5.1.2 on 2025-04-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_alter_proyecto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('ley', 'Proyecto de Ley'), ('resolucion', 'Proyecto de Resolución'), ('expediente', 'Proyecto de Expediente')], default='ley', max_length=20),
        ),
        migrations.AlterField(
            model_name='rutacomision',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('tratandose', 'Archivo'), ('aprobado', 'Despacho'), ('desaprobado', 'En cartera')], default='pendiente', max_length=20),
        ),
    ]
