# Generated by Django 5.1.2 on 2025-04-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_alter_proyecto_tipo_alter_rutacomision_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='es_proyecto_diputada',
            field=models.BooleanField(default=False, help_text="Si está marcado, el proyecto aparecerá en 'Mis Proyectos' de la diputada"),
        ),
    ]
