# Generated by Django 5.1.2 on 2025-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_remove_proyecto_historial_categorias_and_more'),
        ('usuario', '0002_alter_perfil_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='categoria',
        ),
        migrations.AddField(
            model_name='perfil',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='asesores', to='proyectos.categoria'),
        ),
    ]
