# Generated by Django 5.1.2 on 2025-03-15 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_temario_creado_por_alter_proyecto_categoria_and_more'),
        ('usuario', '0003_remove_perfil_categoria_perfil_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='proyectos.categoria'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
